### ISSUE TITLE
gamemode swapper update when

### ISSUE THREAD

**Issue by SomeGDPerson123** [Capeling/Goodbye-Unnecessary-Buttons#5]
Gamemode Swapper was my FAVORITE mod back then, and EVERYONE used it in Globed. When will it update for 2.206 and Geode v3? I'm just asking here because... you don't read the issues tab on the gamemode swapper page...

**Comment by SomeGDPerson123** [comment]
bro didn't even want to answer 💀
whatever

**Comment by capeling** [comment]
harassing me for the mod isnt going to make me port it, leave me alone

**Comment by SomeGDPerson123** [comment]
you shouldve just said you didn't want to port the mod jeez
